
FROM ubuntu:24.04
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl bash build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN bash -c "\
    export NVM_DIR=/root/.nvm && \
    mkdir -p \$NVM_DIR && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    . \$NVM_DIR/nvm.sh && \
    nvm install 24 && \
    nvm use 24 && \
    nvm alias default 24 && \
    ln -sf \$NVM_DIR/versions/node/v24*/bin/node /usr/bin/node && \
    ln -sf \$NVM_DIR/versions/node/v24*/bin/npm /usr/bin/npm && \
    node -v && npm -v \
"

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8888

CMD ["npm", "start"]
