FROM node:16

WORKDIR /usr/src/app

#COPY package*.json ./

# Stelle sicher, dass npm auf die neueste Version aktualisiert wird

#RUN npm install

COPY . .

EXPOSE 3000

#CMD ["npm", "start"]
